version: '3'

tasks:
  tidy:
    cmd: go mod tidy

  subpub-proto:
    cmds:
      - protoc -I ./contracts subpub.proto --go_out=./internal/gen/go --go_opt=paths=source_relative --go-grpc_out=./internal/gen/go --go-grpc_opt=paths=source_relative
      - task: tidy
